server:
  port: 0

spring:
  application:
    name: config-server
  profiles:
    active:
      - native
  cloud:
    config:
      server:
        native:
          search-locations:
            - classpath:/config/stats/{application}
            - classpath:/config/core/{application}
            - classpath:/config/infra/{application}
eureka:
  instance:
    instance-id: ${spring.application.name}:${random.value}
  client:
    service-url:
      defaultZone: http://${EUREKA_HOSTNAME:localhost}:${EUREKA_PORT:8761}/eureka/