server:
  port: 8080

spring:
  cloud:
    gateway:
#      discovery.locator.enabled: true
      routes:
#comment-service
        - id: main_admin_comments_route
          uri: lb://comment-service
          predicates:
            - Path=/admin/comments/**,/users/{userId}/events/{eventId}/comments/**
#request-service
        - id: request_route
          uri: lb://request-service
          predicates:
            - Path=/requests/**,/users/{userId}/events/{eventId}/requests,/users/{userId}/requests/**
#rate-service
        - id: rating_route
          uri: lb://rating-service
          predicates:
            - Path=/rate/**,/users/{userId}/events/{eventId}/rate
#subscription-service
        - id: subscription_route
          uri: lb://subscription-service
          predicates:
            - Path=/users/{userId}/subscriptions/**
#stats-service
        - id: stat_hit_route
          uri: lb://stats-server
          predicates:
            - Path=/hit/**
            - Method=POST
        - id: stat_stats_route
          uri: lb://stats-server
          predicates:
            - Path=/stats/**
            - Method=GET
#compilation-service
        - id: main_admin_compilations_route
          uri: lb://compilation-service
          predicates:
            - Path=/admin/compilations/**
            - Method=POST,DELETE,PATCH
        - id: main_compilations_route
          uri: lb://compilation-service
          predicates:
            - Path=/compilations/**
            - Method=GET
#category-service
        - id: main_admin_categories_route
          uri: lb://category-service
          predicates:
            - Path=/admin/categories/**
            - Method=POST,DELETE,PATCH
        - id: main_categories_route
          uri: lb://category-service
          predicates:
            - Path=/categories/**
            - Method=GET
#event-service
        - id: main_admin_events_route
          uri: lb://event-service
          predicates:
            - Path=/admin/events/**
            - Method=GET,PATCH
        - id: main_events_route
          uri: lb://event-service
          predicates:
            - Path=/events/**,/users/{userId}/events/**
#user-service
        - id: main_users_route
          uri: lb://user-service
          predicates:
            - Path=/users/**
            - Method=GET,POST,PATCH,DELETE
        - id: main_admin_users_route
          uri: lb://user-service
          predicates:
            - Path=/admin/users/**
            - Method=GET,POST,DELETE

logging:
  level:
    org.springframework: ERROR
    org.zalando.logbook: TRACE